### ISSUE TITLE
char

### ISSUE THREAD

**Issue by Linkwarrior75** [Linkwarrior75/Jeff-Mod-X#7]
_comfy char_

**THE BEST CHAR YOU WILL EVER SI ON**

_bob bobson_
**THIS CHAR I AMAZIN**
I RATE THIS 6.9 OUT IOF 10

**Comment by Linkwarrior75** [comment]
**_THA SOUND PRETY COMFY INNIT_**
_**WERE DO I BUY DIS COMFY CHAR?**_

**Comment by Linkwarrior75** [comment]
HAHAHAHAHAHAHAHAH I WILL CLOSE THIS ISSUE HAHAHAHAHHAHAHAHHAH

**Comment by Linkwarrior75** [comment]
**NO DONT**

**Comment by Linkwarrior75** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Linkwarrior75** [comment]
HOW WILL I CONTRIBUTE TO THE _CONOMY_AND GIVE THEM MY POGGERS MONEY

**Comment by Linkwarrior75** [comment]
GOODBYE ISSUE YOU ARE NO LONGIER ISUE

**Comment by Linkwarrior75** [comment]
### _**IAMISSUEREOPENERMAN**_

**Comment by Linkwarrior75** [comment]
WOH! IT ### _**ISSUEOPENERMAN**_!!!!!!!!!!!!!!

**Comment by Linkwarrior75** [comment]
I A M i s s u e c l o s e r g i r l

**Comment by Linkwarrior75** [comment]
I AM GOD

**Comment by Linkwarrior75** [comment]
woh

**Comment by Linkwarrior75** [comment]
no weh

**Comment by Linkwarrior75** [comment]
I SHALL KEEP THIS i s s u e OPEN WITH MY LIFE

**Comment by Linkwarrior75** [comment]
god?

**Comment by Linkwarrior75** [comment]
YES?

**Comment by Linkwarrior75** [comment]
were do i contribute to econome and by char?

**Comment by Linkwarrior75** [comment]
THE REAL CHAR WAS THE FRIENDS WE MADE ALONG THE WAY

**Comment by Linkwarrior75** [comment]
but char comfeh

**Comment by Linkwarrior75** [comment]
NO YOU CANT HAVE CHAR

**Comment by Linkwarrior75** [comment]
do you have last char????????????!

**Comment by Linkwarrior75** [comment]
BYE

**Comment by Linkwarrior75** [comment]
_comfy char_
 _**HEY ALL CHARS ARE BACK**_
_only for 69.69 amogus toys_

**Comment by Linkwarrior75** [comment]
I ONLY HAVE 69.68 AMOOGUS TOYS CAN I HAVE CHAR

**Comment by Linkwarrior75** [comment]
_no_

**Comment by Linkwarrior75** [comment]
_i am going to explode char_

**Comment by Linkwarrior75** [comment]
NOOOOOOOOOOOOOOOOOOOOOO

**Comment by Linkwarrior75** [comment]
no dont i still need to contribute to econome

**Comment by Linkwarrior75** [comment]
### _**IAMISSUEOPENERMANANDIAMDISSAPOINTED**_

**Comment by Linkwarrior75** [comment]
_no i will explode char and destroy econome_

**Comment by Linkwarrior75** [comment]
BREAKING NEWS: CHAR BURNING IN MCDONALDS

**Comment by Linkwarrior75** [comment]
i a m i s s u e c l o s e r m a n

i h a v e d e c i d e d t o j o i n t e a m c a p i t a l i s m

c h a r m u s t n o t d i e

w e w i l l p r e v a i l

**Comment by Linkwarrior75** [comment]
_god has joined team capitalism_

**Comment by Linkwarrior75** [comment]
### _**ISSUEOPENERMANHASJOINEDTEAMCAPITALISM**_

**Comment by Linkwarrior75** [comment]
_random guy has joined team capitalism_

**Comment by Linkwarrior75** [comment]
w i t h o u r p o w e r

**Comment by Linkwarrior75** [comment]
WE WILL PUT

**Comment by Linkwarrior75** [comment]
### _**CHARS**_

**Comment by Linkwarrior75** [comment]
back in stock.

**Comment by Linkwarrior75** [comment]
_NO YOU ARE ALL TOO POWERFUL_

_THIS IS NOT THE LAST YOU WILL SEE OF ME_

_I WILL STEAL YOUR MONEY ONE DAY_

AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

_YOUR CAPITALISM POWER IS TOO STRONG_

_YOU ARE TOO STRONG_

AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Linkwarrior75** [comment]
w e m u s t t a k e t h e c h a r s

**Comment by Linkwarrior75** [comment]
WE MUST TAKE THE CHARS

**Comment by Linkwarrior75** [comment]
### _**WE MUST TAKE THE CHARS**_

**Comment by Linkwarrior75** [comment]
we must take the chars

**Comment by Linkwarrior75** [comment]
_NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO_

**Comment by FunctionalMetatable** [comment]
buy one get 1000000 free

**Comment by FunctionalMetatable** [comment]
aldi price match

**Comment by Linkwarrior75** [comment]
**_CHARS ARE BACK IN STOCK_**

**_SIT ON CHAR IN STYLE WITH NEW CHAR_**

**Comment by FunctionalMetatable** [comment]
> **_CHARS ARE BACK IN STOCK_**
> 
> **_SIT ON CHAR IN STYLE WITH NEW CHAR_**

yae

**Comment by Linkwarrior75** [comment]
CHARS ARE BACK
BUY THEM FOR [insert walmart price match here]!
